language: ruby
rvm:
  - 2.3.1
before_install:
  - gem install bundler
before_script:
  - bundle install
  - cp config/database.yml.travis config/database.yml
  - cp config/secrets.yml.travis config/secrets.yml
  - bundle exec rake db:create
  - bundle exec rake db:migrate
script:
  - bundle exec rspec
